
export const nodeTypes = {
  DATABASE: 'DATABASE',
  DIRECTORY: 'DIRECTORY',
  DRIVE: 'DRIVE',
  FILE: 'FILE',
  MACHINE: 'MACHINE',
  MACHINE_CLUSTER: 'MACHINE_CLUSTER',
  PRINTER: 'PRINTER',
};

export const NODE_PATH_DELIMITER = '/';
